name: Check Syntax and Run Tests

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8
      run: |
        pip install flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are style issues, Python syntax errors, or undefined names
        flake8 . --count --show-source --statistics
    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install jax jaxlib
        pip install flax
        pip install .
    - name: Install pytest
      run: |
        pip install pytest pytest-cov
        pip install coveralls
    - name: Test with pytest
      run: |
        coverage run --source=e3nn-jax -m pytest --doctest-modules --ignore=docs/ --ignore=examples/ .
    # - name: Upload to coveralls
    #   if: github.event_name == 'push'
    #   run: |
    #     COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} coveralls
